/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ArcBounty {
  export type BountyStruct = {
    id: BigNumberish;
    client: AddressLike;
    amount: BigNumberish;
    title: string;
    description: string;
    category: string;
    deadline: BigNumberish;
    maxSubmissions: BigNumberish;
    createdAt: BigNumberish;
    closedAt: BigNumberish;
    status: BigNumberish;
  };

  export type BountyStructOutput = [
    id: bigint,
    client: string,
    amount: bigint,
    title: string,
    description: string,
    category: string,
    deadline: bigint,
    maxSubmissions: bigint,
    createdAt: bigint,
    closedAt: bigint,
    status: bigint
  ] & {
    id: bigint;
    client: string;
    amount: bigint;
    title: string;
    description: string;
    category: string;
    deadline: bigint;
    maxSubmissions: bigint;
    createdAt: bigint;
    closedAt: bigint;
    status: bigint;
  };

  export type ReviewStruct = {
    bountyId: BigNumberish;
    reviewer: AddressLike;
    reviewee: AddressLike;
    rating: BigNumberish;
    comment: string;
    createdAt: BigNumberish;
    fromClient: boolean;
  };

  export type ReviewStructOutput = [
    bountyId: bigint,
    reviewer: string,
    reviewee: string,
    rating: bigint,
    comment: string,
    createdAt: bigint,
    fromClient: boolean
  ] & {
    bountyId: bigint;
    reviewer: string;
    reviewee: string;
    rating: bigint;
    comment: string;
    createdAt: bigint;
    fromClient: boolean;
  };

  export type SubmissionStruct = {
    id: BigNumberish;
    contributor: AddressLike;
    url: string;
    submittedAt: BigNumberish;
    approved: boolean;
  };

  export type SubmissionStructOutput = [
    id: bigint,
    contributor: string,
    url: string,
    submittedAt: bigint,
    approved: boolean
  ] & {
    id: bigint;
    contributor: string;
    url: string;
    submittedAt: bigint;
    approved: boolean;
  };

  export type UserStatsStruct = {
    jobsCompleted: BigNumberish;
    jobsPosted: BigNumberish;
    totalEarned: BigNumberish;
    totalPaid: BigNumberish;
    ratingSum: BigNumberish;
    ratingCount: BigNumberish;
  };

  export type UserStatsStructOutput = [
    jobsCompleted: bigint,
    jobsPosted: bigint,
    totalEarned: bigint,
    totalPaid: bigint,
    ratingSum: bigint,
    ratingCount: bigint
  ] & {
    jobsCompleted: bigint;
    jobsPosted: bigint;
    totalEarned: bigint;
    totalPaid: bigint;
    ratingSum: bigint;
    ratingCount: bigint;
  };
}

export interface ArcBountyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveWork"
      | "cancelBounty"
      | "createBounty"
      | "getAllBounties"
      | "getBountiesByClient"
      | "getBounty"
      | "getReviewsReceived"
      | "getSubmissions"
      | "getUserStats"
      | "getUsers"
      | "hasReviewed"
      | "hasSubmitted"
      | "markDisputed"
      | "submitReview"
      | "submitWork"
      | "totalBounties"
      | "winnerOf"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyCancelled"
      | "BountyCreated"
      | "BountyDisputed"
      | "ReviewSubmitted"
      | "WorkApproved"
      | "WorkSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveWork",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllBounties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBountiesByClient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReviewsReceived",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmissions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getUsers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markDisputed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReview",
    values: [BigNumberish, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBounties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winnerOf",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveWork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllBounties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBountiesByClient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReviewsReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBounties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winnerOf", data: BytesLike): Result;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [
    id: BigNumberish,
    client: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, client: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    client: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    client: AddressLike,
    amount: BigNumberish,
    title: string
  ];
  export type OutputTuple = [
    id: bigint,
    client: string,
    amount: bigint,
    title: string
  ];
  export interface OutputObject {
    id: bigint;
    client: string;
    amount: bigint;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyDisputedEvent {
  export type InputTuple = [id: BigNumberish, reporter: AddressLike];
  export type OutputTuple = [id: bigint, reporter: string];
  export interface OutputObject {
    id: bigint;
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewSubmittedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    reviewer: AddressLike,
    reviewee: AddressLike,
    rating: BigNumberish,
    fromClient: boolean
  ];
  export type OutputTuple = [
    bountyId: bigint,
    reviewer: string,
    reviewee: string,
    rating: bigint,
    fromClient: boolean
  ];
  export interface OutputObject {
    bountyId: bigint;
    reviewer: string;
    reviewee: string;
    rating: bigint;
    fromClient: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkApprovedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    submissionId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    submissionId: bigint,
    winner: string,
    amount: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    submissionId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    submissionId: BigNumberish,
    contributor: AddressLike
  ];
  export type OutputTuple = [
    bountyId: bigint,
    submissionId: bigint,
    contributor: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    submissionId: bigint;
    contributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcBounty extends BaseContract {
  connect(runner?: ContractRunner | null): ArcBounty;
  waitForDeployment(): Promise<this>;

  interface: ArcBountyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveWork: TypedContractMethod<
    [bountyId: BigNumberish, submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBounty: TypedContractMethod<
    [
      title: string,
      description: string,
      category: string,
      deadline: BigNumberish,
      maxSubmissions: BigNumberish
    ],
    [void],
    "payable"
  >;

  getAllBounties: TypedContractMethod<
    [],
    [ArcBounty.BountyStructOutput[]],
    "view"
  >;

  getBountiesByClient: TypedContractMethod<
    [client: AddressLike],
    [ArcBounty.BountyStructOutput[]],
    "view"
  >;

  getBounty: TypedContractMethod<
    [id: BigNumberish],
    [ArcBounty.BountyStructOutput],
    "view"
  >;

  getReviewsReceived: TypedContractMethod<
    [user: AddressLike],
    [ArcBounty.ReviewStructOutput[]],
    "view"
  >;

  getSubmissions: TypedContractMethod<
    [id: BigNumberish],
    [ArcBounty.SubmissionStructOutput[]],
    "view"
  >;

  getUserStats: TypedContractMethod<
    [user: AddressLike],
    [ArcBounty.UserStatsStructOutput],
    "view"
  >;

  getUsers: TypedContractMethod<[], [string[]], "view">;

  hasReviewed: TypedContractMethod<
    [bountyId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  hasSubmitted: TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  markDisputed: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitReview: TypedContractMethod<
    [
      bountyId: BigNumberish,
      reviewee: AddressLike,
      rating: BigNumberish,
      comment: string
    ],
    [void],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<
    [bountyId: BigNumberish, url: string],
    [void],
    "nonpayable"
  >;

  totalBounties: TypedContractMethod<[], [bigint], "view">;

  winnerOf: TypedContractMethod<[id: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveWork"
  ): TypedContractMethod<
    [bountyId: BigNumberish, submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      category: string,
      deadline: BigNumberish,
      maxSubmissions: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAllBounties"
  ): TypedContractMethod<[], [ArcBounty.BountyStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getBountiesByClient"
  ): TypedContractMethod<
    [client: AddressLike],
    [ArcBounty.BountyStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBounty"
  ): TypedContractMethod<
    [id: BigNumberish],
    [ArcBounty.BountyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReviewsReceived"
  ): TypedContractMethod<
    [user: AddressLike],
    [ArcBounty.ReviewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmissions"
  ): TypedContractMethod<
    [id: BigNumberish],
    [ArcBounty.SubmissionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [ArcBounty.UserStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUsers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [bountyId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDisputed"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitReview"
  ): TypedContractMethod<
    [
      bountyId: BigNumberish,
      reviewee: AddressLike,
      rating: BigNumberish,
      comment: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<
    [bountyId: BigNumberish, url: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalBounties"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "winnerOf"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;

  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BountyDisputed"
  ): TypedContractEvent<
    BountyDisputedEvent.InputTuple,
    BountyDisputedEvent.OutputTuple,
    BountyDisputedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewSubmitted"
  ): TypedContractEvent<
    ReviewSubmittedEvent.InputTuple,
    ReviewSubmittedEvent.OutputTuple,
    ReviewSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "WorkApproved"
  ): TypedContractEvent<
    WorkApprovedEvent.InputTuple,
    WorkApprovedEvent.OutputTuple,
    WorkApprovedEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;

  filters: {
    "BountyCancelled(uint256,address,uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyCreated(uint256,address,uint256,string)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "BountyDisputed(uint256,address)": TypedContractEvent<
      BountyDisputedEvent.InputTuple,
      BountyDisputedEvent.OutputTuple,
      BountyDisputedEvent.OutputObject
    >;
    BountyDisputed: TypedContractEvent<
      BountyDisputedEvent.InputTuple,
      BountyDisputedEvent.OutputTuple,
      BountyDisputedEvent.OutputObject
    >;

    "ReviewSubmitted(uint256,address,address,uint8,bool)": TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
    ReviewSubmitted: TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;

    "WorkApproved(uint256,uint256,address,uint256)": TypedContractEvent<
      WorkApprovedEvent.InputTuple,
      WorkApprovedEvent.OutputTuple,
      WorkApprovedEvent.OutputObject
    >;
    WorkApproved: TypedContractEvent<
      WorkApprovedEvent.InputTuple,
      WorkApprovedEvent.OutputTuple,
      WorkApprovedEvent.OutputObject
    >;

    "WorkSubmitted(uint256,uint256,address)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
  };
}
